### ISSUE TITLE
[BUG] hacs doesn't work in latest release 

### ISSUE THREAD

**Issue by chripede** [linuxserver/docker-homeassistant#104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

hacs fails to load during startup of the newest container https://hub.docker.com/layers/linuxserver/homeassistant/2024.6.4/images/sha256-8b1a6668178086b15ce34afbc2814196580722023d4d34eac5d6b873fc688592?context=explore

Reverting to 2024.6.4-ls276 makes it work again

### Steps To Reproduce

Update to newest build with DOCKER_MODS'='linuxserver/mods:homeassistant-hacs

### Environment

```markdown
- OS: unRAID
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run
  -d
  --name='homeassistant'
  --net='host'
  -e TZ="Europe/Paris"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="unRAID"
  -e HOST_CONTAINERNAME="homeassistant"
  -e 'TCP_PORT_8123'='8123'
  -e 'DOCKER_MODS'='linuxserver/mods:homeassistant-hacs'
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8123]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/homeassistant-logo.png'
  -v '/mnt/cache/appdata/homeassistant/media/':'/media':'rw'
  -v '/mnt/cache/appdata/homeassistant/config/':'/config':'rw' 'lscr.io/linuxserver/homeassistant:latest'
```

### Container logs

```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/homeassistant/loader.py", line 1052, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/util/loop.py", line 131, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/hacs/__init__.py", line 12, in <module>
    from aiogithubapi import AIOGitHubAPIException, GitHub, GitHubAPI
  File "/usr/local/lib/python3.12/site-packages/aiogithubapi/__init__.py", line 20, in <module>
    from .device import GitHubDeviceAPI
  File "/usr/local/lib/python3.12/site-packages/aiogithubapi/device.py", line 14, in <module>
    from .client import GitHubClient
  File "/usr/local/lib/python3.12/site-packages/aiogithubapi/client.py", line 27, in <module>
    from .legacy.client import AIOGitHubAPIClient as LegacyAIOGitHubAPIClient
  File "/usr/local/lib/python3.12/site-packages/aiogithubapi/legacy/client.py", line 15, in <module>
    from ..helpers import async_call_api
  File "/usr/local/lib/python3.12/site-packages/aiogithubapi/helpers.py", line 8, in <module>
    from sigstore.verify import (
  File "/usr/local/lib/python3.12/site-packages/sigstore/verify/__init__.py", line 54, in <module>
    from sigstore.verify.models import (
  File "/usr/local/lib/python3.12/site-packages/sigstore/verify/models.py", line 30, in <module>
    from sigstore._internal.rekor import RekorClient
  File "/usr/local/lib/python3.12/site-packages/sigstore/_internal/rekor/__init__.py", line 19, in <module>
    from .client import RekorClient
  File "/usr/local/lib/python3.12/site-packages/sigstore/_internal/rekor/client.py", line 45, in <module>
    class RekorBundle(BaseModel):
  File "pydantic/main.py", line 286, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/main.py", line 807, in pydantic.main.BaseModel.__try_update_forward_refs__
  File "pydantic/typing.py", line 554, in pydantic.typing.update_model_forward_refs
  File "pydantic/typing.py", line 520, in pydantic.typing.update_field_forward_refs
  File "pydantic/typing.py", line 66, in pydantic.typing.evaluate_forwardref
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/homeassistant/loader.py", line 992, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/loader.py", line 1063, in _get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.hacs

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/homeassistant/loader.py", line 1052, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/util/loop.py", line 131, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/hacs/__init__.py", line 12, in <module>
    from aiogithubapi import AIOGitHubAPIException, GitHub, GitHubAPI
  File "/usr/local/lib/python3.12/site-packages/aiogithubapi/__init__.py", line 20, in <module>
    from .device import GitHubDeviceAPI
  File "/usr/local/lib/python3.12/site-packages/aiogithubapi/device.py", line 14, in <module>
    from .client import GitHubClient
  File "/usr/local/lib/python3.12/site-packages/aiogithubapi/client.py", line 27, in <module>
    from .legacy.client import AIOGitHubAPIClient as LegacyAIOGitHubAPIClient
  File "/usr/local/lib/python3.12/site-packages/aiogithubapi/legacy/client.py", line 15, in <module>
    from ..helpers import async_call_api
  File "/usr/local/lib/python3.12/site-packages/aiogithubapi/helpers.py", line 8, in <module>
    from sigstore.verify import (
  File "/usr/local/lib/python3.12/site-packages/sigstore/verify/__init__.py", line 54, in <module>
    from sigstore.verify.models import (
  File "/usr/local/lib/python3.12/site-packages/sigstore/verify/models.py", line 30, in <module>
    from sigstore._internal.rekor import RekorClient
  File "/usr/local/lib/python3.12/site-packages/sigstore/_internal/rekor/__init__.py", line 19, in <module>
    from .client import RekorClient
  File "/usr/local/lib/python3.12/site-packages/sigstore/_internal/rekor/client.py", line 45, in <module>
    class RekorBundle(BaseModel):
  File "pydantic/main.py", line 286, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/main.py", line 807, in pydantic.main.BaseModel.__try_update_forward_refs__
  File "pydantic/typing.py", line 554, in pydantic.typing.update_model_forward_refs
  File "pydantic/typing.py", line 520, in pydantic.typing.update_field_forward_refs
  File "pydantic/typing.py", line 66, in pydantic.typing.evaluate_forwardref
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/homeassistant/setup.py", line 320, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/loader.py", line 1012, in async_get_component
    self._component_future.result()
  File "/usr/local/lib/python3.12/site-packages/homeassistant/loader.py", line 1004, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/loader.py", line 1063, in _get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.hacs
```

**Comment by b2un0** [comment]
relates to 
https://github.com/hacs/integration/issues/3785

**Comment by Shagon94** [comment]
Can confirm that something in 2024.6.4 breaks HACS. Current workaround is to use `lscr.io/linuxserver/homeassistant:2024.6.3` as mentioned above.

**Comment by aptalca** [comment]
I'm on 2024.6.4 and HACS works fine. 

It could be a custom integration needing a newer version of a dependency that is not compatible.

I only have three custom integrations, frigate, frigate-card and mini-graph-card. Those are fine.

**Comment by Shagon94** [comment]
I have the following custom integrations:
- SamsungTV Smart
- Config Editor
- HACS itself

Let me know if you need any logs or anything else to get to the bottom of this, all I can see is that 2024.6.4 breaks HACS so it doesn't even load, while 2024.6.3 works as expected.

**Comment by aptalca** [comment]
I take it back. I do have the issue. But it's not 2024.6.4. The issue occurs with our latest os package updates that seemed to update python to 3.12.4. That should not have happened.

I'll look into it this afternoon.

https://github.com/linuxserver/docker-homeassistant/commit/6a384834d420add6a88b93784c04dd416d31a7fd#diff-41567ece253e75278bc44ff9e68adc494e505e96f75c4f9cc692579f82d1dc46R1290

**Comment by PhAzE-Variance** [comment]
This is related to pydantic. Version in this image is 1.10.15 but needs 1.10.16 for HACS

**Comment by aptalca** [comment]
The immediate issue here is that HA's deps are a nightmare due to thousand something py packages installed. Therefore we try to stay as close as possible to upstream versions for everything. While that doesn't ensure things won't break, but if something breaks, upstream will push for a fix, whereas if we stray and something breaks in our image only, we get no support from upstream and little to no support from integration devs.

In this case, we had a bug in our mechanism where we detect the upstream python version. The complication is that HA uses 2 layers of baseimages. One is version pinned by release date, but the other is not. HA manually times and staggers their docker builds and their images use whatever was latest at build time. If we try to do that later, we may end up using a newer version that what HA used a few days ago because they pushed new updates to that baseimage since.

That's why we ended up building an image with py 3.12.4 instead of 3.12.2.

The linked PR will check and compare the dates of the upstream releases and the baseimage pushes to use the same baseimage versions as the intended version being built.

**Comment by PhAzE-Variance** [comment]
Thanks for the explanation, makes sense to me. What is the best fix for this at the moment, to downgrade or will a new image be pushed with the older python version?

**Comment by aptalca** [comment]
PR should be merged soon and there will be a new image shortly after. I locally tested it and it works fine.
