### ISSUE TITLE
CFFI Version Mistmatch

### ISSUE THREAD

**Issue by GossamerSolid** [linuxserver/docker-homeassistant#16]
I replicated this by pulling the latest tag (2021.7.4-ls31) and running the ZHA module using a ConBee II.

When you boot home assistant, the ZHA module will not initialize.

Here's the output from the home assistant logs:

`Logger: homeassistant.setup
Source: .local/lib/python3.8/site-packages/cffi/api.py:54
First occurred: 4:26:13 PM (1 occurrences)
Last logged: 4:26:13 PM

Setup failed for zha: unknown error
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/homeassistant/setup.py", line 201, in _async_setup_component
    component = integration.get_component()
  File "/usr/lib/python3.8/site-packages/homeassistant/loader.py", line 490, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/homeassistant/components/zha/__init__.py", line 7, in <module>
    from zhaquirks import setup as setup_quirks
  File "/usr/lib/python3.8/site-packages/zhaquirks/__init__.py", line 9, in <module>
    import zigpy.device
  File "/usr/lib/python3.8/site-packages/zigpy/device.py", line 20, in <module>
    import zigpy.endpoint
  File "/usr/lib/python3.8/site-packages/zigpy/endpoint.py", line 12, in <module>
    import zigpy.util
  File "/usr/lib/python3.8/site-packages/zigpy/util.py", line 10, in <module>
    from Crypto.Cipher import AES
  File "/usr/lib/python3.8/site-packages/Crypto/Cipher/__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "/usr/lib/python3.8/site-packages/Crypto/Cipher/_mode_ecb.py", line 29, in <module>
    from Crypto.Util._raw_api import (load_pycryptodome_raw_lib,
  File "/usr/lib/python3.8/site-packages/Crypto/Util/_raw_api.py", line 80, in <module>
    ffi = FFI()
  File "/config/.local/lib/python3.8/site-packages/cffi/api.py", line 54, in __init__
    raise Exception("Version mismatch: this is the 'cffi' package version %s, located in %r.  When we import the top-level '_cffi_backend' extension module, we get version %s, located in %r.  The two versions should be equal; check your installation." % (
Exception: Version mismatch: this is the 'cffi' package version 1.14.5, located in '/config/.local/lib/python3.8/site-packages/cffi/api.py'.  When we import the top-level '_cffi_backend' extension module, we get version 1.14.6, located in '/usr/lib/python3.8/site-packages/_cffi_backend.cpython-38-x86_64-linux-gnu.so'.  The two versions should be equal; check your installation.`

**Comment by tobbenb** [comment]
I guess the problem here is that home assistant core wants one version and the extension another version. If that is the case, there isn't much we can do about it other than wait for the versions to be bumped. 
I'll have to look at it when I get some time.

Please use the issue template we supply. Next time we might not look at the issue until you supply all info.

**Comment by GossamerSolid** [comment]
> I guess the problem here is that home assistant core wants one version and the extension another version. If that is the case, there isn't much we can do about it other than wait for the versions to be bumped.

To fix it on my side, I grabbed the CFFI wheel for linux x86_x64. Extracted it using 7-zip. Pulled the python module code out and slapped it in /config/.local/lib/python3.8/site-packages/cffi/ on the docker instance.

That fixed it.
