### ISSUE TITLE
No module named 'psycopg2._psycopg' after updating from version-2021.9.5 to version-2021.9.6

### ISSUE THREAD

**Issue by kennethso168** [linuxserver/docker-homeassistant#22]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

I have a stack with homeassistant with postgres as backend. After upgrading from version-2021.9.5 to version-2021.9.6, home assistant failed to start. I see No module named 'psycopg2._psycopg' in the log.
------------------------------

## Expected Behavior

Home assistant should start successfully.

## Current Behavior

Home assistant does not start.

## Steps to Reproduce

1. Start the following stack in portainer
2. Set postgresql as backend as instructed in https://www.home-assistant.io/integrations/recorder/
```
recorder:
  db_url: postgresql://homeassistant:<password_redacted>@localhost/homeassistant
```
3. Start home assistant, the startup fails
4. Change tag to version-2021.9.5 in yaml
5.  Home assistant can start

## Environment
**OS:** Linux Mint
**CPU architecture:** x86_64
**How docker service was installed:**

From repo

## Command used to create docker container (run/create/compose/screenshot)

Portainer stack with the following yaml:
```
version: "3.7"

services:
    postdb1:
        container_name: postdb1
        network_mode: host
        restart: unless-stopped
        image: postgres:13.3
        volumes:
            - /opt/appdata/homeassistant/postdb:/var/lib/postgresql/data
            - /etc/localtime:/etc/localtime:ro
            - /etc/passwd:/etc/passwd:ro
        environment:
            - POSTGRES_USER=homeassistant
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - 5432:5432
        user: 1000:1000
    mqtt:
        image: eclipse-mosquitto:latest
        container_name: mqtt
        restart: unless-stopped
        ports:
          - 1883:1883
          - 9001:9001
        volumes:
          - /opt/appdata/mqtt/data:/mosquitto/data
          - /opt/appdata/mqtt/config:/mosquitto/config
          - /opt/appdata/mqtt/log:/mosquitto/log
        network_mode: "host"
        environment:
          - TZ=Asia/Hong_Kong
    homeassistant: 
        image: ghcr.io/linuxserver/homeassistant:version-2021.9.6
        container_name: homeassistant
        network_mode: host
        depends_on: 
            - postdb1
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Hong_Kong
        volumes:
            - /opt/appdata/homeassistant/config:/config
        ports:
            - 8123:8123
        devices:
          - /dev/ttyACM0
        restart: unless-stopped
    node-red:
        image: nodered/node-red:latest
        container_name: node-red
        network_mode: host
        depends_on:
          - homeassistant
        environment:
          - TZ=Asia/Hong_Kong
        ports:
          - "1880:1880"
          # Join
          - "1820:1820"
        volumes:
          - /opt/appdata/nodered:/data
        user: 1000:1000
        restart: unless-stopped
```

## Docker logs

```

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.

[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] 01-envfile: executing... 

[cont-init.d] 01-envfile: exited 0.

[cont-init.d] 10-adduser: executing... 


-------------------------------------

          _         ()

         | |  ___   _    __

         | | / __| | |  /  \ 

         | | \__ \ | | | () |

         |_| |___/ |_|  \__/



Brought to you by linuxserver.io

-------------------------------------


To support LSIO projects visit:

https://www.linuxserver.io/donate/

-------------------------------------

GID/UID

-------------------------------------


User uid:    1000

User gid:    1000

-------------------------------------


[cont-init.d] 10-adduser: exited 0.

[cont-init.d] 50-config: executing... 

[cont-init.d] 50-config: exited 0.

[cont-init.d] 60-usb-gid: executing... 

[cont-init.d] 60-usb-gid: exited 0.

[cont-init.d] 90-custom-folders: executing... 

[cont-init.d] 90-custom-folders: exited 0.

[cont-init.d] 99-custom-files: executing... 

[custom-init] no custom files found exiting...

[cont-init.d] 99-custom-files: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.

Failed to set capabilities on file `/usr/bin/python3.8' (No such file or directory)

usage: setcap [-h] [-q] [-v] [-n <rootid>] (-r|-|<caps>) <filename> [ ... (-r|-|<capsN>) <filenameN> ]


 Note <filename> must be a regular (non-symlink) file.

 -r          remove capability from file

 -           read capability text from stdin

 <capsN>     cap_from_text(3) formatted file capability


 -h          this message and exit status 0

 -q          quietly

 -v          validate supplied capability matches file

 -n <rootid> write a user namespace limited capability

 --license   display the license info

2021-09-13 22:36:17 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration samsungtv_encrypted which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2021-09-13 22:36:17 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2021-09-13 22:36:17 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2021-09-13 22:36:17 INFO (MainThread) [homeassistant.setup] Setup of domain logger took 0.0 seconds

2021-09-13 22:36:17 INFO (MainThread) [homeassistant.setup] Setting up http

2021-09-13 22:36:17 ERROR (Recorder) [homeassistant.components.recorder] Error during connection setup to postgresql://homeassistant:<password_redacted>@localhost/homeassistant: No module named 'psycopg2._psycopg' (retrying in 3 seconds)

Traceback (most recent call last):

  File "/usr/lib/python3.9/site-packages/homeassistant/components/recorder/__init__.py", line 680, in _setup_recorder

    self._setup_connection()

  File "/usr/lib/python3.9/site-packages/homeassistant/components/recorder/__init__.py", line 960, in _setup_connection

    self.engine = create_engine(self.db_url, **kwargs)

  File "<string>", line 2, in create_engine

  File "/usr/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned

    return fn(*args, **kwargs)

  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 548, in create_engine

    dbapi = dialect_cls.dbapi(**dbapi_args)

  File "/usr/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 793, in dbapi

    import psycopg2

  File "/usr/lib/python3.9/site-packages/psycopg2/__init__.py", line 51, in <module>

    from psycopg2._psycopg import (                     # noqa

ModuleNotFoundError: No module named 'psycopg2._psycopg'

2021-09-13 22:36:18 INFO (MainThread) [homeassistant.setup] Setup of domain http took 0.3 seconds

2021-09-13 22:36:18 INFO (MainThread) [homeassistant.setup] Setting up system_log

2021-09-13 22:36:18 INFO (MainThread) [homeassistant.setup] Setup of domain system_log took 0.0 seconds

2021-09-13 22:36:20 ERROR (Recorder) [homeassistant.components.recorder] Error during connection setup to postgresql://homeassistant:<password_redacted>@localhost/homeassistant: No module named 'psycopg2._psycopg' (retrying in 3 seconds)

Traceback (most recent call last):

  File "/usr/lib/python3.9/site-packages/homeassistant/components/recorder/__init__.py", line 680, in _setup_recorder

    self._setup_connection()

  File "/usr/lib/python3.9/site-packages/homeassistant/components/recorder/__init__.py", line 960, in _setup_connection

    self.engine = create_engine(self.db_url, **kwargs)

  File "<string>", line 2, in create_engine

  File "/usr/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned

    return fn(*args, **kwargs)

  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 548, in create_engine

    dbapi = dialect_cls.dbapi(**dbapi_args)

  File "/usr/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 793, in dbapi

    import psycopg2

  File "/usr/lib/python3.9/site-packages/psycopg2/__init__.py", line 51, in <module>

    from psycopg2._psycopg import (                     # noqa

ModuleNotFoundError: No module named 'psycopg2._psycopg'

...
```

**Comment by aptalca** [comment]
weird, psycopg2 is installed in the build: https://ci.linuxserver.io/blue/organizations/jenkins/Docker-Pipeline-Builders%2Fdocker-homeassistant/detail/main/184/pipeline/123#step-138-log-2134

**Comment by aptalca** [comment]
This line is also suspect: `Failed to set capabilities on file `/usr/bin/python3.8' (No such file or directory)`
I'm not sure where it's coming from. Perhaps a plugin installed manually?
This image has py3.9 and not py3.8

**Comment by kennethso168** [comment]
I think my home assistant custom component may have messed up something as when I execute an interactive shell in the container and run `python3`, the version is 3.8, not 3.9.

To exclude the effect of custom component, I started a new stack with only the clean image in portainer:
```
version: "3.7"

services:
    homeassistant: 
        image: ghcr.io/linuxserver/homeassistant:version-2021.9.6
        container_name: homeassistant2

        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Hong_Kong
        ports:
            - 8124:8123
        restart: unless-stopped
```

I execute an interactive bash shell in the container. I can see psycopg2 is installed, and the python version is ok, but there is still the error No module named 'psycopg2._psycopg'

```
root@ff5fc249c01d:/# pip3 list | grep psycopg2
WARNING: The directory '/config/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
psycopg2                          2.9.1
WARNING: You are using pip version 20.2; however, version 21.2.4 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
root@ff5fc249c01d:/# python3
Python 3.9.5 (default, May 12 2021, 20:44:22) 
[GCC 10.3.1 20210424] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import psycopg2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/psycopg2/__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
ModuleNotFoundError: No module named 'psycopg2._psycopg'
```

**Comment by kennethso168** [comment]
I can confirm that the latest tag now works. Thanks a lot!
