### ISSUE TITLE
[BUG] Requirements for smartir not found: ['aiofiles==0.6.0'].

### ISSUE THREAD

**Issue by rwtallant13** [linuxserver/docker-homeassistant#74]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Custom plugin smartir (https://github.com/smartHomeHub/SmartIR) no longer works. pip states that the package needed is installed but plugin complains it is missing.

### Expected Behavior

custom plugin should work with aiofiles installed

### Steps To Reproduce

update to alpine rebase

install smart ir custom integration either manually or with HACS

Plugin will not work and will throw errors in logs

### Environment

```markdown
- OS: debian 12
- How docker service was installed:  package manager
```

### CPU architecture

x86-64

### Docker creation

```bash
homeassistant:
    image: lscr.io/linuxserver/homeassistant
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./homeassistant:/config
    restart: always
```

### Container logs

```bash
Attaching to homeassistant
[36mhomeassistant     |[0m [migrations] started
[36mhomeassistant     |[0m [migrations] no migrations found
[36mhomeassistant     |[0m ───────────────────────────────────────
[36mhomeassistant     |[0m 
[36mhomeassistant     |[0m       ██╗     ███████╗██╗ ██████╗ 
[36mhomeassistant     |[0m       ██║     ██╔════╝██║██╔═══██╗
[36mhomeassistant     |[0m       ██║     ███████╗██║██║   ██║
[36mhomeassistant     |[0m       ██║     ╚════██║██║██║   ██║
[36mhomeassistant     |[0m       ███████╗███████║██║╚██████╔╝
[36mhomeassistant     |[0m       ╚══════╝╚══════╝╚═╝ ╚═════╝ 
[36mhomeassistant     |[0m 
[36mhomeassistant     |[0m    Brought to you by linuxserver.io
[36mhomeassistant     |[0m ───────────────────────────────────────
[36mhomeassistant     |[0m 
[36mhomeassistant     |[0m To support LSIO projects visit:
[36mhomeassistant     |[0m https://www.linuxserver.io/donate/
[36mhomeassistant     |[0m 
[36mhomeassistant     |[0m ───────────────────────────────────────
[36mhomeassistant     |[0m GID/UID
[36mhomeassistant     |[0m ───────────────────────────────────────
[36mhomeassistant     |[0m 
[36mhomeassistant     |[0m User UID:    1000
[36mhomeassistant     |[0m User GID:    1000
[36mhomeassistant     |[0m ───────────────────────────────────────
[36mhomeassistant     |[0m 
[36mhomeassistant     |[0m [custom-init] No custom files found, skipping...
[36mhomeassistant     |[0m [33m2023-06-08 22:36:23.897 WARNING (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/configuration.yaml contains duplicate key "sensor". Check lines 11 and 32[0m
[36mhomeassistant     |[0m [33m2023-06-08 22:36:23.908 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration smartir which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[36mhomeassistant     |[0m [33m2023-06-08 22:36:23.908 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[36mhomeassistant     |[0m [33m2023-06-08 22:36:23.908 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[36mhomeassistant     |[0m [33m2023-06-08 22:36:23.909 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration scheduler which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[36mhomeassistant     |[0m [33m2023-06-08 22:36:23.909 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration ui_lovelace_minimalist which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[36mhomeassistant     |[0m [33m2023-06-08 22:36:23.909 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration auto_backup which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[36mhomeassistant     |[0m [33m2023-06-08 22:36:23.909 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration dwains_dashboard which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[36mhomeassistant     |[0m [33m2023-06-08 22:36:23.909 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration adaptive_lighting which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[36mhomeassistant     |[0m [31m2023-06-08 22:36:27.183 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform shelly
[36mhomeassistant     |[0m Traceback (most recent call last):
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/components/sensor/__init__.py", line 583, in state
[36mhomeassistant     |[0m     numerical_value = float(value)  # type:ignore[arg-type]
[36mhomeassistant     |[0m                       ^^^^^^^^^^^^
[36mhomeassistant     |[0m ValueError: could not convert string to float: 'unavailable'
[36mhomeassistant     |[0m 
[36mhomeassistant     |[0m The above exception was the direct cause of the following exception:
[36mhomeassistant     |[0m 
[36mhomeassistant     |[0m Traceback (most recent call last):
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 471, in async_add_entities
[36mhomeassistant     |[0m     await asyncio.gather(*tasks)
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 749, in _async_add_entity
[36mhomeassistant     |[0m     await entity.add_to_platform_finish()
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 850, in add_to_platform_finish
[36mhomeassistant     |[0m     self.async_write_ha_state()
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 590, in async_write_ha_state
[36mhomeassistant     |[0m     self._async_write_ha_state()
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state
[36mhomeassistant     |[0m     state = self._stringify_state(available)
[36mhomeassistant     |[0m             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 596, in _stringify_state
[36mhomeassistant     |[0m     if (state := self.state) is None:
[36mhomeassistant     |[0m                  ^^^^^^^^^^
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/components/sensor/__init__.py", line 585, in state
[36mhomeassistant     |[0m     raise ValueError(
[36mhomeassistant     |[0m ValueError: Sensor sensor.shelly_button_battery has device class 'battery', state class 'None' unit 'None' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'unavailable' (<class 'str'>)[0m
[36mhomeassistant     |[0m [31m2023-06-08 22:36:27.186 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up shelly platform for sensor
[36mhomeassistant     |[0m Traceback (most recent call last):
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/components/sensor/__init__.py", line 583, in state
[36mhomeassistant     |[0m     numerical_value = float(value)  # type:ignore[arg-type]
[36mhomeassistant     |[0m                       ^^^^^^^^^^^^
[36mhomeassistant     |[0m ValueError: could not convert string to float: 'unavailable'
[36mhomeassistant     |[0m 
[36mhomeassistant     |[0m The above exception was the direct cause of the following exception:
[36mhomeassistant     |[0m 
[36mhomeassistant     |[0m Traceback (most recent call last):
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 328, in _async_setup_platform
[36mhomeassistant     |[0m     await asyncio.gather(*pending)
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 471, in async_add_entities
[36mhomeassistant     |[0m     await asyncio.gather(*tasks)
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 749, in _async_add_entity
[36mhomeassistant     |[0m     await entity.add_to_platform_finish()
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 850, in add_to_platform_finish
[36mhomeassistant     |[0m     self.async_write_ha_state()
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 590, in async_write_ha_state
[36mhomeassistant     |[0m     self._async_write_ha_state()
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state
[36mhomeassistant     |[0m     state = self._stringify_state(available)
[36mhomeassistant     |[0m             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 596, in _stringify_state
[36mhomeassistant     |[0m     if (state := self.state) is None:
[36mhomeassistant     |[0m                  ^^^^^^^^^^
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/components/sensor/__init__.py", line 585, in state
[36mhomeassistant     |[0m     raise ValueError(
[36mhomeassistant     |[0m ValueError: Sensor sensor.shelly_button_battery has device class 'battery', state class 'None' unit 'None' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'unavailable' (<class 'str'>)[0m
[36mhomeassistant     |[0m [ls.io-init] done.
[36mhomeassistant     |[0m [31m2023-06-08 22:36:31.181 ERROR (SyncWorker_5) [homeassistant.util.package] Unable to install package aiofiles==0.6.0: ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: 'WHEEL'
[36mhomeassistant     |[0m Check the permissions.
[36mhomeassistant     |[0m 
[36mhomeassistant     |[0m WARNING: You are using pip version 22.0.4; however, version 23.1.2 is available.
[36mhomeassistant     |[0m You should consider upgrading via the '/lsiopy/bin/python3 -m pip install --upgrade pip' command.[0m
[36mhomeassistant     |[0m [31m2023-06-08 22:36:32.306 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform tplink
[36mhomeassistant     |[0m Traceback (most recent call last):
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 471, in async_add_entities
[36mhomeassistant     |[0m     await asyncio.gather(*tasks)
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 528, in _async_add_entity
[36mhomeassistant     |[0m     entity.add_to_platform_start(
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/components/sensor/__init__.py", line 216, in add_to_platform_start
[36mhomeassistant     |[0m     self._async_read_entity_options()
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/components/sensor/__init__.py", line 774, in _async_read_entity_options
[36mhomeassistant     |[0m     registry.async_update_entity_options(
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_registry.py", line 940, in async_update_entity_options
[36mhomeassistant     |[0m     old = self.entities[entity_id]
[36mhomeassistant     |[0m           ~~~~~~~~~~~~~^^^^^^^^^^^
[36mhomeassistant     |[0m   File "/usr/lib/python3.11/collections/__init__.py", line 1124, in __getitem__
[36mhomeassistant     |[0m     raise KeyError(key)
[36mhomeassistant     |[0m KeyError: None[0m
[36mhomeassistant     |[0m [31m2023-06-08 22:36:32.308 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up tplink platform for sensor
[36mhomeassistant     |[0m Traceback (most recent call last):
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 328, in _async_setup_platform
[36mhomeassistant     |[0m     await asyncio.gather(*pending)
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 471, in async_add_entities
[36mhomeassistant     |[0m     await asyncio.gather(*tasks)
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 528, in _async_add_entity
[36mhomeassistant     |[0m     entity.add_to_platform_start(
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/components/sensor/__init__.py", line 216, in add_to_platform_start
[36mhomeassistant     |[0m     self._async_read_entity_options()
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/components/sensor/__init__.py", line 774, in _async_read_entity_options
[36mhomeassistant     |[0m     registry.async_update_entity_options(
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_registry.py", line 940, in async_update_entity_options
[36mhomeassistant     |[0m     old = self.entities[entity_id]
[36mhomeassistant     |[0m           ~~~~~~~~~~~~~^^^^^^^^^^^
[36mhomeassistant     |[0m   File "/usr/lib/python3.11/collections/__init__.py", line 1124, in __getitem__
[36mhomeassistant     |[0m     raise KeyError(key)
[36mhomeassistant     |[0m KeyError: None[0m
[36mhomeassistant     |[0m [33m2023-06-08 22:36:35.154 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Lava Lamp EP10(US)' for tplink integration not ready yet: Unable to connect to the device: 192.168.2.133: [Errno 113] Connect call failed ('192.168.2.133', 9999); Retrying in background[0m
[36mhomeassistant     |[0m [33m2023-06-08 22:36:35.155 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Bottom Lamp KL125(US)' for tplink integration not ready yet: Unable to connect to the device: 192.168.2.162: [Errno 113] Connect call failed ('192.168.2.162', 9999); Retrying in background[0m
[36mhomeassistant     |[0m [31m2023-06-08 22:36:35.168 ERROR (SyncWorker_5) [homeassistant.util.package] Unable to install package aiofiles==0.6.0: WARNING: Ignoring invalid distribution -iofiles (/lsiopy/lib/python3.11/site-packages)
[36mhomeassistant     |[0m WARNING: Ignoring invalid distribution -iofiles (/lsiopy/lib/python3.11/site-packages)
[36mhomeassistant     |[0m WARNING: Ignoring invalid distribution -iofiles (/lsiopy/lib/python3.11/site-packages)
[36mhomeassistant     |[0m     WARNING: Ignoring invalid distribution -iofiles (/lsiopy/lib/python3.11/site-packages)
[36mhomeassistant     |[0m ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: 'WHEEL'
[36mhomeassistant     |[0m Check the permissions.
[36mhomeassistant     |[0m 
[36mhomeassistant     |[0m WARNING: Ignoring invalid distribution -iofiles (/lsiopy/lib/python3.11/site-packages)
[36mhomeassistant     |[0m WARNING: Ignoring invalid distribution -iofiles (/lsiopy/lib/python3.11/site-packages)
[36mhomeassistant     |[0m WARNING: Ignoring invalid distribution -iofiles (/lsiopy/lib/python3.11/site-packages)
[36mhomeassistant     |[0m WARNING: You are using pip version 22.0.4; however, version 23.1.2 is available.
[36mhomeassistant     |[0m You should consider upgrading via the '/lsiopy/bin/python3 -m pip install --upgrade pip' command.[0m
[36mhomeassistant     |[0m [31m2023-06-08 22:36:39.517 ERROR (SyncWorker_5) [homeassistant.util.package] Unable to install package aiofiles==0.6.0: WARNING: Ignoring invalid distribution -iofiles (/lsiopy/lib/python3.11/site-packages)
[36mhomeassistant     |[0m WARNING: Ignoring invalid distribution - (/lsiopy/lib/python3.11/site-packages)
[36mhomeassistant     |[0m WARNING: Ignoring invalid distribution -iofiles (/lsiopy/lib/python3.11/site-packages)
[36mhomeassistant     |[0m WARNING: Ignoring invalid distribution - (/lsiopy/lib/python3.11/site-packages)
[36mhomeassistant     |[0m WARNING: Ignoring invalid distribution -iofiles (/lsiopy/lib/python3.11/site-packages)
[36mhomeassistant     |[0m WARNING: Ignoring invalid distribution - (/lsiopy/lib/python3.11/site-packages)
[36mhomeassistant     |[0m     WARNING: Ignoring invalid distribution -iofiles (/lsiopy/lib/python3.11/site-packages)
[36mhomeassistant     |[0m     WARNING: Ignoring invalid distribution - (/lsiopy/lib/python3.11/site-packages)
[36mhomeassistant     |[0m ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: 'WHEEL'
[36mhomeassistant     |[0m Check the permissions.
[36mhomeassistant     |[0m 
[36mhomeassistant     |[0m WARNING: Ignoring invalid distribution -iofiles (/lsiopy/lib/python3.11/site-packages)
[36mhomeassistant     |[0m WARNING: Ignoring invalid distribution - (/lsiopy/lib/python3.11/site-packages)
[36mhomeassistant     |[0m WARNING: Ignoring invalid distribution -iofiles (/lsiopy/lib/python3.11/site-packages)
[36mhomeassistant     |[0m WARNING: Ignoring invalid distribution - (/lsiopy/lib/python3.11/site-packages)
[36mhomeassistant     |[0m WARNING: Ignoring invalid distribution -iofiles (/lsiopy/lib/python3.11/site-packages)
[36mhomeassistant     |[0m WARNING: Ignoring invalid distribution - (/lsiopy/lib/python3.11/site-packages)
[36mhomeassistant     |[0m WARNING: You are using pip version 22.0.4; however, version 23.1.2 is available.
[36mhomeassistant     |[0m You should consider upgrading via the '/lsiopy/bin/python3 -m pip install --upgrade pip' command.[0m
[36mhomeassistant     |[0m [31m2023-06-08 22:36:39.518 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration smartir: Requirements for smartir not found: ['aiofiles==0.6.0'].[0m
[36mhomeassistant     |[0m [31m2023-06-08 22:36:39.518 ERROR (MainThread) [homeassistant.config] Platform error: climate - Integration 'smartir' not found.[0m
[36mhomeassistant     |[0m [31m2023-06-08 22:36:40.325 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform tautulli
[36mhomeassistant     |[0m Traceback (most recent call last):
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 471, in async_add_entities
[36mhomeassistant     |[0m     await asyncio.gather(*tasks)
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 528, in _async_add_entity
[36mhomeassistant     |[0m     entity.add_to_platform_start(
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/components/sensor/__init__.py", line 216, in add_to_platform_start
[36mhomeassistant     |[0m     self._async_read_entity_options()
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/components/sensor/__init__.py", line 774, in _async_read_entity_options
[36mhomeassistant     |[0m     registry.async_update_entity_options(
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_registry.py", line 940, in async_update_entity_options
[36mhomeassistant     |[0m     old = self.entities[entity_id]
[36mhomeassistant     |[0m           ~~~~~~~~~~~~~^^^^^^^^^^^
[36mhomeassistant     |[0m   File "/usr/lib/python3.11/collections/__init__.py", line 1124, in __getitem__
[36mhomeassistant     |[0m     raise KeyError(key)
[36mhomeassistant     |[0m KeyError: None[0m
[36mhomeassistant     |[0m [31m2023-06-08 22:36:40.385 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up tautulli platform for sensor
[36mhomeassistant     |[0m Traceback (most recent call last):
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 328, in _async_setup_platform
[36mhomeassistant     |[0m     await asyncio.gather(*pending)
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 471, in async_add_entities
[36mhomeassistant     |[0m     await asyncio.gather(*tasks)
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 528, in _async_add_entity
[36mhomeassistant     |[0m     entity.add_to_platform_start(
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/components/sensor/__init__.py", line 216, in add_to_platform_start
[36mhomeassistant     |[0m     self._async_read_entity_options()
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/components/sensor/__init__.py", line 774, in _async_read_entity_options
[36mhomeassistant     |[0m     registry.async_update_entity_options(
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_registry.py", line 940, in async_update_entity_options
[36mhomeassistant     |[0m     old = self.entities[entity_id]
[36mhomeassistant     |[0m           ~~~~~~~~~~~~~^^^^^^^^^^^
[36mhomeassistant     |[0m   File "/usr/lib/python3.11/collections/__init__.py", line 1124, in __getitem__
[36mhomeassistant     |[0m     raise KeyError(key)
[36mhomeassistant     |[0m KeyError: None[0m
[36mhomeassistant     |[0m [31m2023-06-08 22:36:41.284 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform octoprint
[36mhomeassistant     |[0m Traceback (most recent call last):
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 471, in async_add_entities
[36mhomeassistant     |[0m     await asyncio.gather(*tasks)
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 528, in _async_add_entity
[36mhomeassistant     |[0m     entity.add_to_platform_start(
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/components/sensor/__init__.py", line 216, in add_to_platform_start
[36mhomeassistant     |[0m     self._async_read_entity_options()
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/components/sensor/__init__.py", line 774, in _async_read_entity_options
[36mhomeassistant     |[0m     registry.async_update_entity_options(
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_registry.py", line 940, in async_update_entity_options
[36mhomeassistant     |[0m     old = self.entities[entity_id]
[36mhomeassistant     |[0m           ~~~~~~~~~~~~~^^^^^^^^^^^
[36mhomeassistant     |[0m   File "/usr/lib/python3.11/collections/__init__.py", line 1124, in __getitem__
[36mhomeassistant     |[0m     raise KeyError(key)
[36mhomeassistant     |[0m KeyError: None[0m
[36mhomeassistant     |[0m [31m2023-06-08 22:36:41.286 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up octoprint platform for sensor
[36mhomeassistant     |[0m Traceback (most recent call last):
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 328, in _async_setup_platform
[36mhomeassistant     |[0m     await asyncio.gather(*pending)
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 471, in async_add_entities
[36mhomeassistant     |[0m     await asyncio.gather(*tasks)
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 528, in _async_add_entity
[36mhomeassistant     |[0m     entity.add_to_platform_start(
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/components/sensor/__init__.py", line 216, in add_to_platform_start
[36mhomeassistant     |[0m     self._async_read_entity_options()
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/components/sensor/__init__.py", line 774, in _async_read_entity_options
[36mhomeassistant     |[0m     registry.async_update_entity_options(
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_registry.py", line 940, in async_update_entity_options
[36mhomeassistant     |[0m     old = self.entities[entity_id]
[36mhomeassistant     |[0m           ~~~~~~~~~~~~~^^^^^^^^^^^
[36mhomeassistant     |[0m   File "/usr/lib/python3.11/collections/__init__.py", line 1124, in __getitem__
[36mhomeassistant     |[0m     raise KeyError(key)
[36mhomeassistant     |[0m KeyError: None[0m
[36mhomeassistant     |[0m [31m2023-06-08 22:36:41.376 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform lifx
[36mhomeassistant     |[0m Traceback (most recent call last):
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 471, in async_add_entities
[36mhomeassistant     |[0m     await asyncio.gather(*tasks)
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 528, in _async_add_entity
[36mhomeassistant     |[0m     entity.add_to_platform_start(
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/components/sensor/__init__.py", line 216, in add_to_platform_start
[36mhomeassistant     |[0m     self._async_read_entity_options()
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/components/sensor/__init__.py", line 774, in _async_read_entity_options
[36mhomeassistant     |[0m     registry.async_update_entity_options(
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_registry.py", line 940, in async_update_entity_options
[36mhomeassistant     |[0m     old = self.entities[entity_id]
[36mhomeassistant     |[0m           ~~~~~~~~~~~~~^^^^^^^^^^^
[36mhomeassistant     |[0m   File "/usr/lib/python3.11/collections/__init__.py", line 1124, in __getitem__
[36mhomeassistant     |[0m     raise KeyError(key)
[36mhomeassistant     |[0m KeyError: None[0m
[36mhomeassistant     |[0m [31m2023-06-08 22:36:41.378 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up lifx platform for sensor
[36mhomeassistant     |[0m Traceback (most recent call last):
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 328, in _async_setup_platform
[36mhomeassistant     |[0m     await asyncio.gather(*pending)
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 471, in async_add_entities
[36mhomeassistant     |[0m     await asyncio.gather(*tasks)
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 528, in _async_add_entity
[36mhomeassistant     |[0m     entity.add_to_platform_start(
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/components/sensor/__init__.py", line 216, in add_to_platform_start
[36mhomeassistant     |[0m     self._async_read_entity_options()
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/components/sensor/__init__.py", line 774, in _async_read_entity_options
[36mhomeassistant     |[0m     registry.async_update_entity_options(
[36mhomeassistant     |[0m   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_registry.py", line 940, in async_update_entity_options
[36mhomeassistant     |[0m     old = self.entities[entity_id]
[36mhomeassistant     |[0m           ~~~~~~~~~~~~~^^^^^^^^^^^
[36mhomeassistant     |[0m   File "/usr/lib/python3.11/collections/__init__.py", line 1124, in __getitem__
[36mhomeassistant     |[0m     raise KeyError(key)
[36mhomeassistant     |[0m KeyError: None[0m
[36mhomeassistant     |[0m [33m2023-06-08 22:36:51.281 WARNING (MainThread) [homeassistant.config_entries] Config entry 'LIFX Mini 300D0A' for homekit_controller integration not ready yet: Timeout while waiting for connection to device 192.168.2.206:56483; Retrying in background[0m
```

**Comment by aptalca** [comment]
See here: https://github.com/linuxserver/docker-homeassistant/issues/70#issuecomment-1583088612

**Comment by barrelltitor** [comment]
I'm running the latest available image, however I still get similar errors for some integrations:

Setup failed for custom integration eufy_security: Requirements for eufy_security not found: ['websocket-client==1.1.0'].

Is this fix not yet available or am I doing something wrong?

**Comment by Roxedus** [comment]
> Is this fix not yet available or am I doing something wrong?

This issue is *closed* because a fix is released. Open a new issue and provide the requested info

**Comment by aptalca** [comment]
The linked comments above explain it in detail along with 2 different solutions
