### ISSUE TITLE
[BUG] Cannot start container with python error: No module named 'homeassistant'

### ISSUE THREAD

**Issue by Yrlish** [linuxserver/docker-homeassistant#82]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The container cannot start, tries to find the homeassistant python module indefinitely.

### Steps To Reproduce

I pulled the latest tag and restarted the container, previous pull was at 2023-05-19. The old versions works fine, still if I revert back to it.

### Environment

```markdown
- OS: Ubuntu Server and Portainer
- How docker service was installed:
Docker's apt repo
```

### CPU architecture

x86-64

### Docker creation

```bash
Cannot find a way to extract the creation parameters from Portainer. But I inputted the instructions from the README into the GUI.

Haven't changed anything when pulling new latest, previous image worked fine.
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    911
───────────────────────────────────────
Updating pip to HA supported version
Requirement already satisfied: pip<22.1,>=21.0 in /config/lsiopy/lib/python3.11/site-packages (22.0.4)
Requirement already satisfied: setuptools in /config/lsiopy/lib/python3.11/site-packages (68.0.0)
Requirement already satisfied: wheel in /config/lsiopy/lib/python3.11/site-packages (0.40.0)
Setting permissions
[custom-init] No custom files found, skipping...
Traceback (most recent call last):
  File "/lsiopy/bin/hass", line 5, in <module>
    from homeassistant.__main__ import main
ModuleNotFoundError: No module named 'homeassistant'
Traceback (most recent call last):
  File "/lsiopy/bin/hass", line 5, in <module>
    from homeassistant.__main__ import main
ModuleNotFoundError: No module named 'homeassistant'
Traceback (most recent call last):
  File "/lsiopy/bin/hass", line 5, in <module>
    from homeassistant.__main__ import main
ModuleNotFoundError: No module named 'homeassistant'
Traceback (most recent call last):
  File "/lsiopy/bin/hass", line 5, in <module>
    from homeassistant.__main__ import main
ModuleNotFoundError: No module named 'homeassistant'
Traceback (most recent call last):
  File "/lsiopy/bin/hass", line 5, in <module>
    from homeassistant.__main__ import main
ModuleNotFoundError: No module named 'homeassistant'
Traceback (most recent call last):
  File "/lsiopy/bin/hass", line 5, in <module>
    from homeassistant.__main__ import main
ModuleNotFoundError: No module named 'homeassistant'
```

**Comment by Roxedus** [comment]
https://info.linuxserver.io/issues/2023-05-22-portainer/

**Comment by Yrlish** [comment]
@Roxedus So Portainer is to blame here injecting old labels/envs into the new environment? How unfortunate... I've been using it because I was lazy.

Oh well, I have been meaning to restructure my containers and go back to plain Docker Compose files... This just pushes me to do that sooner rather than later, since I cannot update anything rather easily now...
