### ISSUE TITLE
[BUG] Presence of LSIOPY folder causes Docker container loop on start/restart

### ISSUE THREAD

**Issue by armouredking** [linuxserver/docker-homeassistant#85]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If LSIOPY folder exists in HomeAssistant persistent storage folder, I am now unable to restart HASS from the UI. Additionally, stopping and starting the docker container (with sudo docker stop/start) causes the same issue. Likewise, docker compose up also suffers the same.

### Expected Behavior

HASS Docker should start and restart without needing to delete LSIOPY folder any/every time.

### Steps To Reproduce

Attempt to do anything with the container while LSIOPY exists. Remove LSIOPY folder from HASS configuration directory and it will be recreated _and the system will start as expected until next it is downed_. Stop container (or restart service from GUI) and system fails. See logs.

### Environment

- OS: Debian 12 (Bookworm)
- How docker service was installed: Per Docker instructions w/ [Docker repo](https://docs.docker.com/engine/install/debian/) (not using Debian repo)

### CPU architecture

x86-64

### Docker creation

Via Docker Compose alias typically (though as noted above, using other docker commands also does not work)

```bash
alias stackup='sudo docker compose pull && sudo docker compose down && sudo docker compose up -d'
```

Nothing esoteric with configuration, and system was working in July without issue. Other networks are to talk to HASS components (such as MQTT)

```bash
services:
  homeassistant:
    container_name: homeassistant
    hostname: hass
    image: lscr.io/linuxserver/homeassistant:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Phoenix
      - DOCKER_MODS=linuxserver/mods:homeassistant-hacs
    volumes:
      - ./haconfigs:/config
    restart: unless-stopped
    depends_on:
      - mariadb
      - node-red
    networks:
      - frontend
      - backend
      - backend2
      - backend3
```

### Container logs

Without LSIOPY:
```bash
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Adding linuxserver/mods:homeassistant-hacs to container
[mod-init] Downloading linuxserver/mods:homeassistant-hacs from lscr.io
[mod-init] Installing linuxserver/mods:homeassistant-hacs
[mod-init] linuxserver/mods:homeassistant-hacs applied to container
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

Creating venv in /config/lsiopy for runtime use
Updating pip to HA supported version
Collecting pip<22.1,>=21.0
  Downloading pip-22.0.4-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 5.8 MB/s eta 0:00:00
Requirement already satisfied: setuptools in /config/lsiopy/lib/python3.11/site-packages (65.5.0)
Collecting setuptools
  Downloading setuptools-68.0.0-py3-none-any.whl (804 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 804.0/804.0 kB 5.9 MB/s eta 0:00:00
Requirement already satisfied: wheel in /lsiopy/lib/python3.11/site-packages (0.41.1)
Installing collected packages: setuptools, pip
  Attempting uninstall: setuptools
    Found existing installation: setuptools 65.5.0
    Uninstalling setuptools-65.5.0:
      Successfully uninstalled setuptools-65.5.0
  Attempting uninstall: pip
    Found existing installation: pip 23.1.2
    Uninstalling pip-23.1.2:
      Successfully uninstalled pip-23.1.2
Successfully installed pip-22.0.4 setuptools-68.0.0
Setting permissions
**** HACS already installed, skipping ****
[custom-init] No custom files found, skipping...
2023-08-13 11:40:03.623 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-08-13 11:40:03.624 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration homeseer which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-08-13 11:40:03.624 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration frigate which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-08-13 11:40:11.355 INFO (MainThread) [Jellyfin] ---[ START JELLYFINCLIENT ]---
[ls.io-init] done.
```

With LSIOPY:
```bash
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Adding linuxserver/mods:homeassistant-hacs to container
[mod-init] Downloading linuxserver/mods:homeassistant-hacs from lscr.io
[mod-init] Installing linuxserver/mods:homeassistant-hacs
[mod-init] linuxserver/mods:homeassistant-hacs applied to container
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

Updating pip to HA supported version
Traceback (most recent call last):
  File "/config/lsiopy/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
  File "/config/lsiopy/lib/python3.11/site-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/config/lsiopy/lib/python3.11/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/config/lsiopy/lib/python3.11/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/config/lsiopy/lib/python3.11/site-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/config/lsiopy/lib/python3.11/site-packages/pip/_internal/cli/parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/config/lsiopy/lib/python3.11/site-packages/pip/_internal/configuration.py", line 26, in <module>
    from pip._internal.utils.logging import getLogger
  File "/config/lsiopy/lib/python3.11/site-packages/pip/_internal/utils/logging.py", line 27, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "/config/lsiopy/lib/python3.11/site-packages/pip/_internal/utils/misc.py", line 35, in <module>
    from pip._vendor.tenacity import retry, stop_after_delay, wait_fixed
  File "/config/lsiopy/lib/python3.11/site-packages/pip/_vendor/tenacity/__init__.py", line 514, in <module>
    from pip._vendor.tenacity._asyncio import AsyncRetrying  # noqa:E402,I100
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/lsiopy/lib/python3.11/site-packages/pip/_vendor/tenacity/_asyncio.py", line 21, in <module>
    from asyncio import sleep
  File "/config/lsiopy/lib/python3.11/site-packages/asyncio/__init__.py", line 21, in <module>
    from .base_events import *
  File "/config/lsiopy/lib/python3.11/site-packages/asyncio/base_events.py", line 296
    future = tasks.async(future, loop=self)
                   ^^^^^
SyntaxError: invalid syntax
```

Edit: Fix formatting

**Comment by thespad** [comment]
One of your custom integrations is installing an ancient version of the Python asyncio library that isn't compatible with Home Assistant. What you're doing is deleting that library, which will allow HA to start. You need to get the maintainer of the integration to fix their dependencies.

**Comment by armouredking** [comment]
> One of your custom integrations is installing an ancient version of the Python asyncio library that isn't compatible with Home Assistant. What you're doing is deleting that library, which will allow HA to start. You need to get the maintainer of the integration to fix their dependencies.

How can I tell which one is causing the issue?

**Comment by thespad** [comment]
Either by a process of elimitation or by looking at the dependencies for each one to see which packages they're requesting be installed.

**Comment by armouredking** [comment]
Seems to be caused by marthoc's HomeSeer integration. Just disabling it wasn't enough though, had to delete the integration, then delete the HACS repo, then delete the LSIOPY folder again, and now it seems like things are working again. I don't update often so not sure how long it has been broken, I did test back to tags 2023.7.3 with no change so likely been a month or two at least.
